const API='/api';let installations=[],currentId=null,charts={};
const $=s=>document.querySelector(s), content=$('#content');
const apiGet=path=>api(path);
const apiPost=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
const apiPut=(path,body)=>api(path,{method:'PUT',body:JSON.stringify(body)});
const apiDelete=path=>api(path,{method:'DELETE'});
async function api(path,opts={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok){let m='Request failed';try{m=(await r.json()).message||m}catch{}throw Error(m)}return r.status===204?null:r.json()}
function toast(msg,error=false){const d=document.createElement('div');d.className='toast'+(error?' error':'');d.textContent=msg;$('#toast').appendChild(d);setTimeout(()=>d.remove(),3200)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}
function destroyCharts(){Object.values(charts).forEach(c=>c.destroy());charts={}}
function loading(){content.innerHTML='<div class="card empty">Loading SolarShare data…</div>'}
async function init(){ $('#today').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});try{installations=await api('/installations');fillInstallations();currentId=installations[0]?.id||null;await render('dashboard')}catch(e){toast(e.message,true);content.innerHTML='<div class="card empty">Could not load the application. Check MySQL and restart Spring Boot.</div>'}}
function fillInstallations(){const s=$('#installationSelect');s.innerHTML=installations.length?installations.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''):'<option>No installations</option>';if(currentId)s.value=currentId;s.onchange=async()=>{currentId=Number(s.value);await render(document.querySelector('.nav.active')?.dataset.page||'dashboard')}}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#sidebar').classList.remove('open');await render(b.dataset.page)})}
async function render(page){destroyCharts();loading();const titles={dashboard:['Community Dashboard','Real-time rooftop solar overview'],installations:['Installations','Manage community solar assets'],households:['Households','Allocation and usage management'],generation:['Solar Generation','Record and review generated energy'],consumption:['Consumption','Track household energy use'],allocation:['Energy Allocation','See how community generation is distributed'],analytics:['Analytics','Interactive performance insights'],history:['History','Historical generation and consumption records']};$('#pageTitle').textContent=titles[page][0];$('#pageSub').textContent=titles[page][1];try{({dashboard:dashboard,installations:installationsPage,households:householdsPage,generation:generationPage,consumption:consumptionPage,allocation:allocationPage,analytics:analyticsPage,history:historyPage}[page]||dashboard)()}catch(e){toast(e.message,true)}}
async function dashboard(){if(!currentId){content.innerHTML='<div class="card empty">Add an installation to begin.</div>';return}const d=await api(`/installations/${currentId}/dashboard`);content.innerHTML=`<div class="grid kpis"><div class="card kpi"><div class="ico">☀</div><h3>MONTHLY GENERATION</h3><strong>${fmt(d.generation)} <small>kWh</small></strong><small>Solar energy produced</small></div><div class="card kpi"><div class="ico">◒</div><h3>CONSUMPTION</h3><strong>${fmt(d.consumption)} <small>kWh</small></strong><small>Community household usage</small></div><div class="card kpi"><div class="ico">↗</div><h3>ENERGY EXPORTED</h3><strong>${fmt(d.exportedEnergy)} <small>kWh</small></strong><small>Unused allocated solar</small></div><div class="card kpi"><div class="ico">⌂</div><h3>HOUSEHOLDS</h3><strong>${d.householdCount}</strong><small>${fmt(d.capacityKw)} kW installation capacity</small></div></div><div class="grid dashboard-grid"><div class="card wide"><div class="card-head"><h2>Generation vs Consumption</h2><span>Current year</span></div><canvas id="trend"></canvas></div><div class="card"><div class="card-head"><h2>Community summary</h2><span>${d.month}/${d.year}</span></div><div class="statline"><span>Allocated</span><b>${fmt(d.allocatedEnergy)} kWh</b></div><div class="statline"><span>Generation</span><b>${fmt(d.generation)} kWh</b></div><div class="statline"><span>Consumption</span><b>${fmt(d.consumption)} kWh</b></div><div class="statline"><span>Exported</span><b>${fmt(d.exportedEnergy)} kWh</b></div></div></div><div class="card" style="margin-top:18px"><div class="card-head"><h2>Household performance</h2><span>Current month</span></div><div class="table-wrap"><table class="table"><thead><tr><th>HOUSEHOLD</th><th>ALLOCATION</th><th>ALLOCATED</th><th>CONSUMPTION</th><th>EXPORT</th><th>STATUS</th></tr></thead><tbody>${d.households.map(h=>`<tr><td><b>${esc(h.household||'')}</b></td><td>${fmt(Number(h.allocationRatio)*100)}%</td><td>${fmt(h.allocatedEnergy)} kWh</td><td>${fmt(h.consumption)} kWh</td><td>${fmt(h.exportedEnergy)} kWh</td><td><span class="pill">${Number(h.exportedEnergy)>0?'EXPORTING':'USING'}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No households yet.</td></tr>'}</tbody></table></div></div>`;const labels=d.monthlyTrend.map(x=>new Date(2000,x.month-1).toLocaleString(undefined,{month:'short'}));charts.trend=new Chart($('#trend'),{type:'line',data:{labels,datasets:[{label:'Generation',data:d.monthlyTrend.map(x=>x.generation),tension:.35},{label:'Consumption',data:d.monthlyTrend.map(x=>x.consumption),tension:.35}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true}}}})}
async function installationsPage(){content.innerHTML=`<div class="toolbar"><input id="isearch" placeholder="Search installations…"><button class="btn" onclick="openInstallation()">+ Add Installation</button></div><div id="instCards" class="grid cards3"></div>`;const q=$('#isearch');q.oninput=()=>drawInst(q.value);drawInst('')}
function drawInst(q){const list=installations.filter(x=>(x.name+' '+x.location).toLowerCase().includes(q.toLowerCase()));$('#instCards').innerHTML=list.map(x=>`<div class="card"><div class="card-head"><h2>☀ ${esc(x.name)}</h2><span>${x.id}</span></div><p style="color:var(--muted)">${esc(x.location)}</p><div class="statline"><span>Capacity</span><b>${fmt(x.capacityKw)} kW</b></div><div class="statline"><span>Households</span><b>${x.householdCount}</b></div><div class="statline"><span>Total generation</span><b>${fmt(x.totalGeneration)} kWh</b></div><div style="display:flex;gap:8px;margin-top:15px"><button class="btn secondary" onclick="selectInst(${x.id})">Open</button><button class="btn secondary" onclick="editInstallation(${x.id})">Edit</button><button class="btn danger" onclick="deleteInstallation(${x.id})">Delete</button></div></div>`).join('')||'<div class="card empty">No installations found.</div>'}
async function selectInst(id){currentId=id;$('#installationSelect').value=id;await render('dashboard')}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')};function closeModal(){$('#modal').classList.add('hidden')};$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function openInstallation(data={}){openModal(`<h2>${data.id?'Edit':'Add'} Installation</h2><form class="form" id="instForm"><label>Name<input required name="name" value="${esc(data.name)}"></label><label>Location<input required name="location" value="${esc(data.location)}"></label><label>Total Capacity (kW)<input required min="0.01" step="0.01" type="number" name="capacityKw" value="${data.capacityKw||''}"></label><div class="form-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn">Save Installation</button></div></form>`);$('#instForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f);body.capacityKw=Number(body.capacityKw);try{const x=data.id?await api(`/installations/${data.id}`,{method:'PUT',body:JSON.stringify(body)}):await api('/installations',{method:'POST',body:JSON.stringify(body)});toast('Installation saved');closeModal();installations=await api('/installations');currentId=x.id;fillInstallations();render('installations')}catch(err){toast(err.message,true)}}}
function editInstallation(id){openInstallation(installations.find(x=>x.id===id))}async function deleteInstallation(id){if(!confirm('Delete this installation and its records?'))return;try{await api(`/installations/${id}`,{method:'DELETE'});installations=await api('/installations');currentId=installations[0]?.id||null;fillInstallations();toast('Installation deleted');render('installations')}catch(e){toast(e.message,true)}}
async function householdsPage(){
 if(!currentId){content.innerHTML='<div class="card empty">Add an installation first.</div>';return}
 const hs=await api(`/installations/${currentId}/households`);
 content.innerHTML=`<div class="toolbar"><input id="hsearch" placeholder="Search households…"><button class="btn" onclick="openHousehold()">+ Add Household</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>HOUSEHOLD</th><th>OWNER</th><th>ALLOCATION</th><th>ALLOCATED</th><th>CONSUMPTION</th><th>EXPORT</th><th>ACTIONS</th></tr></thead><tbody id="hbody"></tbody></table></div></div>`;
 const draw=()=>{
   const q=$('#hsearch').value.toLowerCase();
   const rows=hs.filter(h=>(h.name+' '+h.ownerName).toLowerCase().includes(q));
   $('#hbody').innerHTML=rows.map(h=>{
     const payload=encodeURIComponent(JSON.stringify(h));
     return `<tr><td><b>${esc(h.name)}</b></td><td>${esc(h.ownerName)}</td><td>${fmt(Number(h.allocationRatio)*100)}%</td><td>${fmt(h.allocatedEnergy)} kWh</td><td>${fmt(h.consumption)} kWh</td><td>${fmt(h.exportedEnergy)} kWh</td><td><button class="btn secondary" onclick="editHouseholdEncoded('${payload}')">Edit</button> <button class="btn danger" onclick="deleteHousehold(${h.id})">Delete</button></td></tr>`;
   }).join('') || '<tr><td colspan="7" class="empty">No households yet.</td></tr>';
 };
 $('#hsearch').oninput=draw;draw();
}
function editHouseholdEncoded(v){openHousehold(JSON.parse(decodeURIComponent(v)))}

function openHousehold(data={}){openModal(`<h2>${data.id?'Edit':'Add'} Household</h2><form class="form" id="hForm"><label>Household Name<input required name="name" value="${esc(data.name)}"></label><label>Owner Name<input required name="ownerName" value="${esc(data.ownerName)}"></label><label>Allocation Ratio (0–1)<input required min="0" max="1" step="0.01" type="number" name="allocationRatio" value="${data.allocationRatio??''}"></label><small style="color:var(--muted)">Example: 0.40 = 40% of available generation.</small><div class="form-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn">Save Household</button></div></form>`);$('#hForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),b=Object.fromEntries(f);b.allocationRatio=Number(b.allocationRatio);try{await api(data.id?`/households/${data.id}`:`/installations/${currentId}/households`,{method:data.id?'PUT':'POST',body:JSON.stringify(b)});toast('Household saved');closeModal();render('households')}catch(err){toast(err.message,true)}}}
async function deleteHousehold(id){if(!confirm('Delete this household and its consumption records?'))return;try{await api(`/households/${id}`,{method:'DELETE'});toast('Household deleted');render('households')}catch(e){toast(e.message,true)}}
async function generationPage(){const rows=currentId?await api(`/installations/${currentId}/generation`):[];content.innerHTML=`<div class="card"><div class="card-head"><h2>Record Generation</h2><span>kWh generated by the selected installation</span></div><form class="toolbar" id="gForm"><input required type="date" name="date"><input required min="0" step="0.01" type="number" name="units" placeholder="Units generated (kWh)"><button class="btn">Record Generation</button></form></div><div class="card" style="margin-top:18px"><div class="card-head"><h2>Generation History</h2></div><table class="table"><thead><tr><th>DATE</th><th>INSTALLATION</th><th>GENERATED</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.date}</td><td>${esc(x.installation)}</td><td>${fmt(x.unitsGenerated)} kWh</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No generation records.</td></tr>'}</tbody></table></div>`;$('#gForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.units=Number(b.units);try{await api(`/installations/${currentId}/generation`,{method:'POST',body:JSON.stringify(b)});toast('Generation recorded');render('generation')}catch(err){toast(err.message,true)}}}
async function getHouseholds(){return currentId?api(`/installations/${currentId}/households`):[]}
async function consumptionPage(){const hs=await getHouseholds();let rows=[];for(const h of hs){const r=await api(`/households/${h.id}/consumption`);rows.push(...r.map(x=>({...x,household:h.name})))}content.innerHTML=`<div class="card"><div class="card-head"><h2>Record Consumption</h2><span>Household meter reading</span></div><form class="toolbar" id="cForm"><select required name="householdId">${hs.map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('')}</select><input required type="date" name="date"><input required min="0" step="0.01" type="number" name="units" placeholder="Units consumed (kWh)"><button class="btn">Record Consumption</button></form></div><div class="card" style="margin-top:18px"><div class="card-head"><h2>Consumption History</h2></div><table class="table"><thead><tr><th>DATE</th><th>HOUSEHOLD</th><th>CONSUMPTION</th></tr></thead><tbody>${rows.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${x.date}</td><td>${esc(x.household)}</td><td>${fmt(x.unitsConsumed)} kWh</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No consumption records.</td></tr>'}</tbody></table></div>`;$('#cForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));const id=b.householdId;delete b.householdId;b.units=Number(b.units);try{await api(`/households/${id}/consumption`,{method:'POST',body:JSON.stringify(b)});toast('Consumption recorded');render('consumption')}catch(err){toast(err.message,true)}}}
async function allocationPage(){if(!currentId){content.innerHTML='<div class="card empty">Add an installation first.</div>';return}const d=await api(`/installations/${currentId}/dashboard`);content.innerHTML=`<div class="card"><div class="card-head"><h2>Energy flow</h2><span>${esc(d.installation)}</span></div><div class="flow"><div>☀<b>Solar Generation</b>${fmt(d.generation)} kWh</div><span class="arrow">→</span><div>◈<b>Allocation</b>${fmt(d.allocatedEnergy)} kWh</div><span class="arrow">→</span><div>⌂<b>Consumption</b>${fmt(d.consumption)} kWh</div><span class="arrow">→</span><div>↗<b>Export</b>${fmt(d.exportedEnergy)} kWh</div></div></div><div class="grid cards3" style="margin-top:18px">${d.households.map(h=>`<div class="card"><div class="card-head"><h2>${esc(h.household)}</h2><b>${fmt(Number(h.allocationRatio)*100)}%</b></div><div class="statline"><span>Allocated solar</span><b>${fmt(h.allocatedEnergy)} kWh</b></div><div class="statline"><span>Consumed</span><b>${fmt(h.consumption)} kWh</b></div><div class="statline"><span>Exported</span><b>${fmt(h.exportedEnergy)} kWh</b></div><div class="progress"><i style="width:${Math.min(100,Number(h.allocationRatio)*100)}%"></i></div></div>`).join('')||'<div class="card empty">No households yet.</div>'}</div>`}
async function analyticsPage(){if(!currentId){content.innerHTML='<div class="card empty">Add an installation first.</div>';return}const d=await api(`/installations/${currentId}/dashboard`);content.innerHTML=`<div class="grid dashboard-grid"><div class="card wide"><div class="card-head"><h2>Annual Generation & Consumption</h2><span>${d.year}</span></div><canvas id="a1"></canvas></div><div class="card"><div class="card-head"><h2>Allocation distribution</h2></div><canvas id="a2"></canvas></div></div><div class="card" style="margin-top:18px"><div class="card-head"><h2>Community performance</h2><span>Current month</span></div><div class="grid cards3">${[['Generation',d.generation,'kWh'],['Consumption',d.consumption,'kWh'],['Export',d.exportedEnergy,'kWh']].map(x=>`<div><small style="color:var(--muted)">${x[0]}</small><h2>${fmt(x[1])} ${x[2]}</h2></div>`).join('')}</div></div>`;const labels=d.monthlyTrend.map(x=>new Date(2000,x.month-1).toLocaleString(undefined,{month:'short'}));charts.a1=new Chart($('#a1'),{type:'bar',data:{labels,datasets:[{label:'Generation',data:d.monthlyTrend.map(x=>x.generation)},{label:'Consumption',data:d.monthlyTrend.map(x=>x.consumption)}]},options:{responsive:true}});charts.a2=new Chart($('#a2'),{type:'doughnut',data:{labels:d.households.map(x=>x.household),datasets:[{data:d.households.map(x=>Number(x.allocationRatio)*100)}]},options:{responsive:true}})}
async function historyPage(){const hs=await getHouseholds();let rows=[];for(const h of hs){const s=await api(`/households/${h.id}/summary/monthly`);rows.push({...s,household:h.name})}content.innerHTML=`<div class="card"><div class="card-head"><h2>Monthly history snapshot</h2><span>Current month; use Analytics for trends</span></div><table class="table"><thead><tr><th>HOUSEHOLD</th><th>MONTH</th><th>ALLOCATED</th><th>CONSUMPTION</th><th>EXPORT</th><th>NET USAGE</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.household)}</td><td>${x.month}/${x.year}</td><td>${fmt(x.allocatedEnergy)} kWh</td><td>${fmt(x.consumption)} kWh</td><td>${fmt(x.exportedEnergy)} kWh</td><td>${fmt(x.netUsage)} kWh</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No historical records available.</td></tr>'}</tbody></table></div>`}
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');nav();init();
